export enum CoreFlowStepCode {
  SourceDocumentReceived = 'SourceDocumentReceived',
  GateInRecorded = 'GateInRecorded',
  ReceiptLineReceived = 'ReceiptLineReceived',
  DiscrepancyRecorded = 'DiscrepancyRecorded',
  QcCompleted = 'QcCompleted',
  LpnConfirmed = 'LpnConfirmed',
  InboundReleasedToPutaway = 'InboundReleasedToPutaway',
  PutawayTaskReleased = 'PutawayTaskReleased',
  PutawayConfirmed = 'PutawayConfirmed',
  InventoryStatusChanged = 'InventoryStatusChanged',
  CycleCountSubmitted = 'CycleCountSubmitted',
  ReplenishmentReleased = 'ReplenishmentReleased',
  OutboundOrderReceived = 'OutboundOrderReceived',
  AllocationCompleted = 'AllocationCompleted',
  ReleasedToWarehouse = 'ReleasedToWarehouse',
  PickConfirmed = 'PickConfirmed',
  PackagePacked = 'PackagePacked',
  PackageReadyForStaging = 'PackageReadyForStaging',
  PackageStaged = 'PackageStaged',
  DockTruckMilestoneRecorded = 'DockTruckMilestoneRecorded',
  LoadingConfirmed = 'LoadingConfirmed',
  GateOutRecorded = 'GateOutRecorded',
  GoodsIssuePosted = 'GoodsIssuePosted',
}
