import { MasterDataOwnershipPolicyDto } from '@modules/MasterData/Application/DTOs/MasterDataOwnershipPolicyDto';
import { DataOwnershipMode } from '@modules/MasterData/Domain/Enums/DataOwnershipMode';
import { MasterDataObjectGroup } from '@modules/MasterData/Domain/Enums/MasterDataObjectGroup';
import { OwnershipPolicyImplementationStatus } from '@modules/MasterData/Domain/Enums/OwnershipPolicyImplementationStatus';
import { SourceOfTruthType } from '@modules/MasterData/Domain/Enums/SourceOfTruthType';

const now = new Date('2026-01-01T00:00:00.000Z');

const policy = (params: Omit<MasterDataOwnershipPolicyDto, 'CreatedAt' | 'UpdatedAt' | 'CreatedBy' | 'UpdatedBy'>) => ({
  ...params,
  CreatedAt: now,
  UpdatedAt: now,
  CreatedBy: null,
  UpdatedBy: null,
});

export const DefaultMasterDataOwnershipPolicies = (): MasterDataOwnershipPolicyDto[] => [
  policy({
    Id: '00000000-0000-0000-0000-000000000601',
    ObjectGroup: MasterDataObjectGroup.Sku,
    DisplayName: 'SKU',
    SourceOfTruthType: SourceOfTruthType.Wms,
    TypicalSourceSystems: ['WMS', 'ERP', 'OMS', 'PIM', 'OwnerMaster'],
    OwnershipMode: DataOwnershipMode.WmsOwnedEditable,
    DirectEditAllowed: true,
    RequiresAudit: true,
    RequiresReason: false,
    RequiresSourceSystem: false,
    RequiresReferenceId: false,
    ImplementationStatus: OwnershipPolicyImplementationStatus.Implemented,
    DeferredToStory: 'FND-UXR-03A',
    PolicyNotes: 'SKU master can be created and maintained directly in WMS UI when no ERP upstream is available.',
    SourceDocRef: 'doc04#14',
  }),
  policy({
    Id: '00000000-0000-0000-0000-000000000602',
    ObjectGroup: MasterDataObjectGroup.UomPack,
    DisplayName: 'UOM/Pack',
    SourceOfTruthType: SourceOfTruthType.Hybrid,
    TypicalSourceSystems: ['ERP', 'OwnerMaster', 'WMS'],
    OwnershipMode: DataOwnershipMode.ExternalImportedConditionalEdit,
    DirectEditAllowed: true,
    RequiresAudit: true,
    RequiresReason: true,
    RequiresSourceSystem: true,
    RequiresReferenceId: true,
    ImplementationStatus: OwnershipPolicyImplementationStatus.Implemented,
    DeferredToStory: 'C5',
    PolicyNotes: 'UOM and pack corrections can affect inventory and require audit enforcement in C5.',
    SourceDocRef: 'doc04#14',
  }),
  policy({
    Id: '00000000-0000-0000-0000-000000000603',
    ObjectGroup: MasterDataObjectGroup.BarcodeAlias,
    DisplayName: 'Barcode/Alias',
    SourceOfTruthType: SourceOfTruthType.Hybrid,
    TypicalSourceSystems: ['ERP', 'OwnerMaster', 'Supplier', 'WMS'],
    OwnershipMode: DataOwnershipMode.ExternalImportedConditionalEdit,
    DirectEditAllowed: true,
    RequiresAudit: true,
    RequiresReason: true,
    RequiresSourceSystem: true,
    RequiresReferenceId: true,
    ImplementationStatus: OwnershipPolicyImplementationStatus.Implemented,
    DeferredToStory: 'C5',
    PolicyNotes: 'Barcode alias is editable with duplicate control and later audit enforcement.',
    SourceDocRef: 'doc04#14',
  }),
  policy({
    Id: '00000000-0000-0000-0000-000000000604',
    ObjectGroup: MasterDataObjectGroup.WarehouseLocation,
    DisplayName: 'Warehouse/Location',
    SourceOfTruthType: SourceOfTruthType.Wms,
    TypicalSourceSystems: ['WMS'],
    OwnershipMode: DataOwnershipMode.WmsOwnedEditable,
    DirectEditAllowed: true,
    RequiresAudit: true,
    RequiresReason: true,
    RequiresSourceSystem: false,
    RequiresReferenceId: false,
    ImplementationStatus: OwnershipPolicyImplementationStatus.Implemented,
    DeferredToStory: 'C5',
    PolicyNotes: 'Warehouse and location are WMS-owned but cannot be silently deleted once used.',
    SourceDocRef: 'doc04#14',
  }),
  policy({
    Id: '00000000-0000-0000-0000-000000000605',
    ObjectGroup: MasterDataObjectGroup.LocationProfile,
    DisplayName: 'Location Profile',
    SourceOfTruthType: SourceOfTruthType.Wms,
    TypicalSourceSystems: ['WMS'],
    OwnershipMode: DataOwnershipMode.WmsOwnedControlled,
    DirectEditAllowed: true,
    RequiresAudit: true,
    RequiresReason: true,
    RequiresSourceSystem: false,
    RequiresReferenceId: false,
    ImplementationStatus: OwnershipPolicyImplementationStatus.Implemented,
    DeferredToStory: 'C5',
    PolicyNotes: 'Location profile changes affect rules and require version/audit enforcement.',
    SourceDocRef: 'doc04#14',
  }),
  policy({
    Id: '00000000-0000-0000-0000-000000000606',
    ObjectGroup: MasterDataObjectGroup.OwnerCustomerSupplier,
    DisplayName: 'Owner/Customer/Supplier',
    SourceOfTruthType: SourceOfTruthType.ExternalSystem,
    TypicalSourceSystems: ['ERP', 'CRM', 'OMS', 'OwnerOnboarding'],
    OwnershipMode: DataOwnershipMode.ExternalOwnedReadOnly,
    DirectEditAllowed: false,
    RequiresAudit: true,
    RequiresReason: true,
    RequiresSourceSystem: true,
    RequiresReferenceId: true,
    ImplementationStatus: OwnershipPolicyImplementationStatus.PartiallyImplemented,
    DeferredToStory: 'C5',
    PolicyNotes: 'Party master data is external-owned or conditional through onboarding.',
    SourceDocRef: 'doc04#14',
  }),
  policy({
    Id: '00000000-0000-0000-0000-000000000607',
    ObjectGroup: MasterDataObjectGroup.InventoryStatus,
    DisplayName: 'Inventory Status',
    SourceOfTruthType: SourceOfTruthType.Wms,
    TypicalSourceSystems: ['WMS'],
    OwnershipMode: DataOwnershipMode.WmsOwnedControlled,
    DirectEditAllowed: true,
    RequiresAudit: true,
    RequiresReason: true,
    RequiresSourceSystem: false,
    RequiresReferenceId: false,
    ImplementationStatus: OwnershipPolicyImplementationStatus.Implemented,
    DeferredToStory: 'C5',
    PolicyNotes: 'Inventory status is core WMS configuration and must be change-controlled.',
    SourceDocRef: 'doc04#14',
  }),
  policy({
    Id: '00000000-0000-0000-0000-000000000608',
    ObjectGroup: MasterDataObjectGroup.LpnSscc,
    DisplayName: 'LPN/SSCC',
    SourceOfTruthType: SourceOfTruthType.Deferred,
    TypicalSourceSystems: ['WMS', 'ExternalSystem'],
    OwnershipMode: DataOwnershipMode.Deferred,
    DirectEditAllowed: false,
    RequiresAudit: true,
    RequiresReason: true,
    RequiresSourceSystem: true,
    RequiresReferenceId: true,
    ImplementationStatus: OwnershipPolicyImplementationStatus.Deferred,
    DeferredToStory: 'V1+',
    PolicyNotes: 'A5 only stores optional LpnCode dimension; full LPN/SSCC lifecycle is deferred.',
    SourceDocRef: 'doc04#14',
  }),
  policy({
    Id: '00000000-0000-0000-0000-000000000609',
    ObjectGroup: MasterDataObjectGroup.ReasonCode,
    DisplayName: 'Reason Code',
    SourceOfTruthType: SourceOfTruthType.Wms,
    TypicalSourceSystems: ['WMS'],
    OwnershipMode: DataOwnershipMode.Deferred,
    DirectEditAllowed: false,
    RequiresAudit: true,
    RequiresReason: false,
    RequiresSourceSystem: false,
    RequiresReferenceId: false,
    ImplementationStatus: OwnershipPolicyImplementationStatus.Deferred,
    DeferredToStory: 'C3',
    PolicyNotes: 'Reason code catalog is completed by C3.',
    SourceDocRef: 'doc04#14',
  }),
];
