import { ControlExceptionSeverity } from '@modules/AccessControl/Domain/Enums/ControlExceptionSeverity';
import { ExceptionState } from '@modules/AccessControl/Domain/Enums/ExceptionState';
import { ReceiptLineDiscrepancySignal } from '@modules/Inbound/Domain/Enums/ReceiptLineDiscrepancySignal';
import { InboundDiscrepancyStatus } from '@modules/Inbound/Domain/Enums/InboundDiscrepancyStatus';
import { InboundDiscrepancyToleranceDecision } from '@modules/Inbound/Domain/Enums/InboundDiscrepancyToleranceDecision';
import { InboundDiscrepancyType } from '@modules/Inbound/Domain/Enums/InboundDiscrepancyType';

export class InboundDiscrepancyEntity {
  public readonly Id: string;
  public ReceiptId: string;
  public ReceiptLineId: string;
  public InboundPlanId: string | null;
  public InboundPlanLineId: string | null;
  public OwnerId: string;
  public OwnerCode: string | null;
  public WarehouseId: string;
  public WarehouseCode: string | null;
  public DiscrepancyType: InboundDiscrepancyType;
  public Signals: ReceiptLineDiscrepancySignal[];
  public Status: InboundDiscrepancyStatus;
  public Severity: ControlExceptionSeverity;
  public ToleranceDecision: InboundDiscrepancyToleranceDecision;
  public ExpectedQuantity: number | null;
  public ActualQuantity: number;
  public ReasonCode: string;
  public ReasonCodeId: string;
  public ReasonNote: string | null;
  public EvidenceRefs: string[];
  public EvidenceJson: Record<string, unknown> | null;
  public RuleCode: string | null;
  public ExceptionCaseId: string;
  public ExceptionState: ExceptionState;
  public IdempotencyKey: string;
  public RecordedAt: Date;
  public RecordedBy: string | null;
  public readonly CreatedAt: Date;
  public UpdatedAt: Date;

  constructor(params: {
    Id: string;
    ReceiptId: string;
    ReceiptLineId: string;
    InboundPlanId: string | null;
    InboundPlanLineId: string | null;
    OwnerId: string;
    OwnerCode?: string | null;
    WarehouseId: string;
    WarehouseCode?: string | null;
    DiscrepancyType: InboundDiscrepancyType;
    Signals?: ReceiptLineDiscrepancySignal[];
    Status: InboundDiscrepancyStatus;
    Severity: ControlExceptionSeverity;
    ToleranceDecision: InboundDiscrepancyToleranceDecision;
    ExpectedQuantity: number | null;
    ActualQuantity: number;
    ReasonCode: string;
    ReasonCodeId: string;
    ReasonNote?: string | null;
    EvidenceRefs?: string[];
    EvidenceJson?: Record<string, unknown> | null;
    RuleCode?: string | null;
    ExceptionCaseId: string;
    ExceptionState: ExceptionState;
    IdempotencyKey: string;
    RecordedAt: Date;
    RecordedBy?: string | null;
    CreatedAt: Date;
    UpdatedAt: Date;
  }) {
    this.Id = params.Id;
    this.ReceiptId = params.ReceiptId;
    this.ReceiptLineId = params.ReceiptLineId;
    this.InboundPlanId = params.InboundPlanId;
    this.InboundPlanLineId = params.InboundPlanLineId;
    this.OwnerId = params.OwnerId;
    this.OwnerCode = params.OwnerCode ?? null;
    this.WarehouseId = params.WarehouseId;
    this.WarehouseCode = params.WarehouseCode ?? null;
    this.DiscrepancyType = params.DiscrepancyType;
    this.Signals = params.Signals ?? [];
    this.Status = params.Status;
    this.Severity = params.Severity;
    this.ToleranceDecision = params.ToleranceDecision;
    this.ExpectedQuantity = params.ExpectedQuantity;
    this.ActualQuantity = params.ActualQuantity;
    this.ReasonCode = params.ReasonCode;
    this.ReasonCodeId = params.ReasonCodeId;
    this.ReasonNote = params.ReasonNote ?? null;
    this.EvidenceRefs = params.EvidenceRefs ?? [];
    this.EvidenceJson = params.EvidenceJson ?? null;
    this.RuleCode = params.RuleCode ?? null;
    this.ExceptionCaseId = params.ExceptionCaseId;
    this.ExceptionState = params.ExceptionState;
    this.IdempotencyKey = params.IdempotencyKey;
    this.RecordedAt = params.RecordedAt;
    this.RecordedBy = params.RecordedBy ?? null;
    this.CreatedAt = params.CreatedAt;
    this.UpdatedAt = params.UpdatedAt;
  }
}
