export class InboundLpnEntity {
  public readonly Id: string;
  public ReceiptId: string;
  public ReceiptLineId: string;
  public InboundPlanId: string | null;
  public InboundPlanLineId: string | null;
  public OwnerId: string;
  public OwnerCode: string | null;
  public WarehouseId: string;
  public WarehouseCode: string | null;
  public SkuId: string;
  public SkuCode: string | null;
  public UomId: string;
  public UomCode: string | null;
  public Quantity: number;
  public LpnCode: string;
  public SsccCode: string | null;
  public ReasonCode: string | null;
  public ReasonCodeId: string | null;
  public ReasonNote: string | null;
  public EvidenceRefs: string[];
  public IdempotencyKey: string;
  public ConfirmedAt: Date;
  public ConfirmedBy: string | null;
  public readonly CreatedAt: Date;
  public UpdatedAt: Date;

  constructor(params: {
    Id: string;
    ReceiptId: string;
    ReceiptLineId: string;
    InboundPlanId: string | null;
    InboundPlanLineId: string | null;
    OwnerId: string;
    OwnerCode?: string | null;
    WarehouseId: string;
    WarehouseCode?: string | null;
    SkuId: string;
    SkuCode?: string | null;
    UomId: string;
    UomCode?: string | null;
    Quantity: number;
    LpnCode: string;
    SsccCode?: string | null;
    ReasonCode?: string | null;
    ReasonCodeId?: string | null;
    ReasonNote?: string | null;
    EvidenceRefs?: string[];
    IdempotencyKey: string;
    ConfirmedAt: Date;
    ConfirmedBy?: string | null;
    CreatedAt: Date;
    UpdatedAt: Date;
  }) {
    this.Id = params.Id;
    this.ReceiptId = params.ReceiptId;
    this.ReceiptLineId = params.ReceiptLineId;
    this.InboundPlanId = params.InboundPlanId;
    this.InboundPlanLineId = params.InboundPlanLineId;
    this.OwnerId = params.OwnerId;
    this.OwnerCode = params.OwnerCode ?? null;
    this.WarehouseId = params.WarehouseId;
    this.WarehouseCode = params.WarehouseCode ?? null;
    this.SkuId = params.SkuId;
    this.SkuCode = params.SkuCode ?? null;
    this.UomId = params.UomId;
    this.UomCode = params.UomCode ?? null;
    this.Quantity = params.Quantity;
    this.LpnCode = params.LpnCode;
    this.SsccCode = params.SsccCode ?? null;
    this.ReasonCode = params.ReasonCode ?? null;
    this.ReasonCodeId = params.ReasonCodeId ?? null;
    this.ReasonNote = params.ReasonNote ?? null;
    this.EvidenceRefs = params.EvidenceRefs ?? [];
    this.IdempotencyKey = params.IdempotencyKey;
    this.ConfirmedAt = params.ConfirmedAt;
    this.ConfirmedBy = params.ConfirmedBy ?? null;
    this.CreatedAt = params.CreatedAt;
    this.UpdatedAt = params.UpdatedAt;
  }
}
