export class InboundPutawayReleaseEntity {
  public readonly Id: string;
  public InboundLpnId: string | null;
  public ReceiptId: string;
  public ReceiptLineId: string;
  public InboundPlanId: string;
  public InboundPlanLineId: string;
  public OwnerId: string;
  public OwnerCode: string | null;
  public WarehouseId: string;
  public WarehouseCode: string | null;
  public SkuId: string;
  public SkuCode: string | null;
  public UomId: string;
  public UomCode: string | null;
  public Quantity: number;
  public LpnCode: string | null;
  public SsccCode: string | null;
  public InventoryStatusCode: string;
  public CurrentLocationId: string | null;
  public CurrentLocationCode: string | null;
  public WarehouseProfileId: string | null;
  public LabelDecision: string | null;
  public LabelReason: string | null;
  public MatchedPrintJobId: string | null;
  public ConstraintJson: Record<string, unknown> | null;
  public OutboxMessageId: string | null;
  public CoreFlowMilestoneId: string | null;
  public ReasonCode: string | null;
  public ReasonCodeId: string | null;
  public ReasonNote: string | null;
  public EvidenceRefs: string[];
  public IdempotencyKey: string;
  public ReleasedAt: Date;
  public ReleasedBy: string | null;
  public readonly CreatedAt: Date;
  public UpdatedAt: Date;

  constructor(params: {
    Id: string;
    InboundLpnId?: string | null;
    ReceiptId: string;
    ReceiptLineId: string;
    InboundPlanId: string;
    InboundPlanLineId: string;
    OwnerId: string;
    OwnerCode?: string | null;
    WarehouseId: string;
    WarehouseCode?: string | null;
    SkuId: string;
    SkuCode?: string | null;
    UomId: string;
    UomCode?: string | null;
    Quantity: number;
    LpnCode?: string | null;
    SsccCode?: string | null;
    InventoryStatusCode: string;
    CurrentLocationId?: string | null;
    CurrentLocationCode?: string | null;
    WarehouseProfileId?: string | null;
    LabelDecision?: string | null;
    LabelReason?: string | null;
    MatchedPrintJobId?: string | null;
    ConstraintJson?: Record<string, unknown> | null;
    OutboxMessageId?: string | null;
    CoreFlowMilestoneId?: string | null;
    ReasonCode?: string | null;
    ReasonCodeId?: string | null;
    ReasonNote?: string | null;
    EvidenceRefs?: string[];
    IdempotencyKey: string;
    ReleasedAt: Date;
    ReleasedBy?: string | null;
    CreatedAt: Date;
    UpdatedAt: Date;
  }) {
    this.Id = params.Id;
    this.InboundLpnId = params.InboundLpnId ?? null;
    this.ReceiptId = params.ReceiptId;
    this.ReceiptLineId = params.ReceiptLineId;
    this.InboundPlanId = params.InboundPlanId;
    this.InboundPlanLineId = params.InboundPlanLineId;
    this.OwnerId = params.OwnerId;
    this.OwnerCode = params.OwnerCode ?? null;
    this.WarehouseId = params.WarehouseId;
    this.WarehouseCode = params.WarehouseCode ?? null;
    this.SkuId = params.SkuId;
    this.SkuCode = params.SkuCode ?? null;
    this.UomId = params.UomId;
    this.UomCode = params.UomCode ?? null;
    this.Quantity = params.Quantity;
    this.LpnCode = params.LpnCode ?? null;
    this.SsccCode = params.SsccCode ?? null;
    this.InventoryStatusCode = params.InventoryStatusCode;
    this.CurrentLocationId = params.CurrentLocationId ?? null;
    this.CurrentLocationCode = params.CurrentLocationCode ?? null;
    this.WarehouseProfileId = params.WarehouseProfileId ?? null;
    this.LabelDecision = params.LabelDecision ?? null;
    this.LabelReason = params.LabelReason ?? null;
    this.MatchedPrintJobId = params.MatchedPrintJobId ?? null;
    this.ConstraintJson = params.ConstraintJson ?? null;
    this.OutboxMessageId = params.OutboxMessageId ?? null;
    this.CoreFlowMilestoneId = params.CoreFlowMilestoneId ?? null;
    this.ReasonCode = params.ReasonCode ?? null;
    this.ReasonCodeId = params.ReasonCodeId ?? null;
    this.ReasonNote = params.ReasonNote ?? null;
    this.EvidenceRefs = params.EvidenceRefs ?? [];
    this.IdempotencyKey = params.IdempotencyKey;
    this.ReleasedAt = params.ReleasedAt;
    this.ReleasedBy = params.ReleasedBy ?? null;
    this.CreatedAt = params.CreatedAt;
    this.UpdatedAt = params.UpdatedAt;
  }
}
