import { QcDispositionCode } from '@modules/Inbound/Domain/Enums/QcDispositionCode';
import { QcResultStatus } from '@modules/Inbound/Domain/Enums/QcResultStatus';

export class QcResultEntity {
  public readonly Id: string;
  public QcTaskId: string;
  public ReceiptId: string;
  public ReceiptLineId: string;
  public InboundPlanId: string;
  public InboundPlanLineId: string;
  public OwnerId: string;
  public OwnerCode: string | null;
  public WarehouseId: string;
  public WarehouseCode: string | null;
  public ResultStatus: QcResultStatus;
  public DispositionCode: QcDispositionCode;
  public InspectedQuantity: number;
  public AcceptedQuantity: number;
  public RejectedQuantity: number;
  public AcceptedInventoryStatusCode: string | null;
  public RejectedInventoryStatusCode: string | null;
  public TargetInventoryStatusCode: string;
  public ReasonCode: string | null;
  public ReasonCodeId: string | null;
  public ReasonNote: string | null;
  public EvidenceRefs: string[];
  public EvidenceJson: Record<string, unknown> | null;
  public IdempotencyKey: string;
  public RecordedAt: Date;
  public RecordedBy: string | null;
  public readonly CreatedAt: Date;
  public UpdatedAt: Date;

  constructor(params: {
    Id: string;
    QcTaskId: string;
    ReceiptId: string;
    ReceiptLineId: string;
    InboundPlanId: string;
    InboundPlanLineId: string;
    OwnerId: string;
    OwnerCode?: string | null;
    WarehouseId: string;
    WarehouseCode?: string | null;
    ResultStatus: QcResultStatus;
    DispositionCode: QcDispositionCode;
    InspectedQuantity: number;
    AcceptedQuantity: number;
    RejectedQuantity: number;
    AcceptedInventoryStatusCode?: string | null;
    RejectedInventoryStatusCode?: string | null;
    TargetInventoryStatusCode: string;
    ReasonCode?: string | null;
    ReasonCodeId?: string | null;
    ReasonNote?: string | null;
    EvidenceRefs?: string[];
    EvidenceJson?: Record<string, unknown> | null;
    IdempotencyKey: string;
    RecordedAt: Date;
    RecordedBy?: string | null;
    CreatedAt: Date;
    UpdatedAt: Date;
  }) {
    this.Id = params.Id;
    this.QcTaskId = params.QcTaskId;
    this.ReceiptId = params.ReceiptId;
    this.ReceiptLineId = params.ReceiptLineId;
    this.InboundPlanId = params.InboundPlanId;
    this.InboundPlanLineId = params.InboundPlanLineId;
    this.OwnerId = params.OwnerId;
    this.OwnerCode = params.OwnerCode ?? null;
    this.WarehouseId = params.WarehouseId;
    this.WarehouseCode = params.WarehouseCode ?? null;
    this.ResultStatus = params.ResultStatus;
    this.DispositionCode = params.DispositionCode;
    this.InspectedQuantity = params.InspectedQuantity;
    this.AcceptedQuantity = params.AcceptedQuantity;
    this.RejectedQuantity = params.RejectedQuantity;
    this.AcceptedInventoryStatusCode = params.AcceptedInventoryStatusCode ?? null;
    this.RejectedInventoryStatusCode = params.RejectedInventoryStatusCode ?? null;
    this.TargetInventoryStatusCode = params.TargetInventoryStatusCode;
    this.ReasonCode = params.ReasonCode ?? null;
    this.ReasonCodeId = params.ReasonCodeId ?? null;
    this.ReasonNote = params.ReasonNote ?? null;
    this.EvidenceRefs = params.EvidenceRefs ?? [];
    this.EvidenceJson = params.EvidenceJson ?? null;
    this.IdempotencyKey = params.IdempotencyKey;
    this.RecordedAt = params.RecordedAt;
    this.RecordedBy = params.RecordedBy ?? null;
    this.CreatedAt = params.CreatedAt;
    this.UpdatedAt = params.UpdatedAt;
  }
}
