import { QcTaskStatus } from '@modules/Inbound/Domain/Enums/QcTaskStatus';

export class QcTaskEntity {
  public readonly Id: string;
  public ReceiptId: string;
  public ReceiptLineId: string;
  public InboundPlanId: string;
  public InboundPlanLineId: string;
  public OwnerId: string;
  public OwnerCode: string | null;
  public WarehouseId: string;
  public WarehouseCode: string | null;
  public SkuId: string;
  public SkuCode: string | null;
  public UomId: string;
  public UomCode: string | null;
  public ActualQuantity: number;
  public TaskStatus: QcTaskStatus;
  public Required: boolean;
  public TriggerReason: string;
  public TriggerPolicyJson: Record<string, unknown> | null;
  public InventoryStatusCode: string;
  public TargetInventoryStatusCode: string | null;
  public ReasonCode: string | null;
  public ReasonCodeId: string | null;
  public ReasonNote: string | null;
  public EvidenceRefs: string[];
  public IdempotencyKey: string;
  public CreatedBy: string | null;
  public UpdatedBy: string | null;
  public readonly CreatedAt: Date;
  public UpdatedAt: Date;

  constructor(params: {
    Id: string;
    ReceiptId: string;
    ReceiptLineId: string;
    InboundPlanId: string;
    InboundPlanLineId: string;
    OwnerId: string;
    OwnerCode?: string | null;
    WarehouseId: string;
    WarehouseCode?: string | null;
    SkuId: string;
    SkuCode?: string | null;
    UomId: string;
    UomCode?: string | null;
    ActualQuantity: number;
    TaskStatus: QcTaskStatus;
    Required: boolean;
    TriggerReason: string;
    TriggerPolicyJson?: Record<string, unknown> | null;
    InventoryStatusCode: string;
    TargetInventoryStatusCode?: string | null;
    ReasonCode?: string | null;
    ReasonCodeId?: string | null;
    ReasonNote?: string | null;
    EvidenceRefs?: string[];
    IdempotencyKey: string;
    CreatedBy?: string | null;
    UpdatedBy?: string | null;
    CreatedAt: Date;
    UpdatedAt: Date;
  }) {
    this.Id = params.Id;
    this.ReceiptId = params.ReceiptId;
    this.ReceiptLineId = params.ReceiptLineId;
    this.InboundPlanId = params.InboundPlanId;
    this.InboundPlanLineId = params.InboundPlanLineId;
    this.OwnerId = params.OwnerId;
    this.OwnerCode = params.OwnerCode ?? null;
    this.WarehouseId = params.WarehouseId;
    this.WarehouseCode = params.WarehouseCode ?? null;
    this.SkuId = params.SkuId;
    this.SkuCode = params.SkuCode ?? null;
    this.UomId = params.UomId;
    this.UomCode = params.UomCode ?? null;
    this.ActualQuantity = params.ActualQuantity;
    this.TaskStatus = params.TaskStatus;
    this.Required = params.Required;
    this.TriggerReason = params.TriggerReason;
    this.TriggerPolicyJson = params.TriggerPolicyJson ?? null;
    this.InventoryStatusCode = params.InventoryStatusCode;
    this.TargetInventoryStatusCode = params.TargetInventoryStatusCode ?? null;
    this.ReasonCode = params.ReasonCode ?? null;
    this.ReasonCodeId = params.ReasonCodeId ?? null;
    this.ReasonNote = params.ReasonNote ?? null;
    this.EvidenceRefs = params.EvidenceRefs ?? [];
    this.IdempotencyKey = params.IdempotencyKey;
    this.CreatedBy = params.CreatedBy ?? null;
    this.UpdatedBy = params.UpdatedBy ?? null;
    this.CreatedAt = params.CreatedAt;
    this.UpdatedAt = params.UpdatedAt;
  }
}
