import { randomUUID } from 'crypto';
import { CycleCountWorkStatus } from '@modules/InventoryExecution/Domain/Enums/CycleCountWorkStatus';

export interface CycleCountWorkEntityProps {
  Id?: string;
  CountCode: string;
  WorkStatus: CycleCountWorkStatus;
  SourceBalanceId: string;
  LockedBalanceId?: string | null;
  OriginalInventoryStatusCode: string;
  WarehouseId: string;
  WarehouseCode?: string | null;
  OwnerId: string;
  OwnerCode?: string | null;
  SkuId: string;
  SkuCode?: string | null;
  LocationId: string;
  LocationCode?: string | null;
  UomId?: string | null;
  UomCode?: string | null;
  LpnCode?: string | null;
  ExpectedQuantity: number;
  CountedQuantity?: number | null;
  VarianceQuantity?: number | null;
  ToleranceQuantity?: number;
  ApprovalRequestId?: string | null;
  LockTransactionId?: string | null;
  SubmitIdempotencyKey?: string | null;
  SubmitPayloadFingerprint?: string | null;
  AdjustmentTransactionId?: string | null;
  AdjustmentIdempotencyKey?: string | null;
  AdjustmentPayloadFingerprint?: string | null;
  UnlockTransactionId?: string | null;
  UnlockIdempotencyKey?: string | null;
  UnlockPayloadFingerprint?: string | null;
  CreateIdempotencyKey: string;
  CreatePayloadFingerprint: string;
  ReasonCode?: string | null;
  ReasonCodeId?: string | null;
  ReasonNote?: string | null;
  EvidenceRefs?: string[];
  CreatedAt?: Date;
  UpdatedAt?: Date;
  CreatedBy?: string | null;
  UpdatedBy?: string | null;
}

export class CycleCountWorkEntity {
  public readonly Id: string;
  public CountCode: string;
  public WorkStatus: CycleCountWorkStatus;
  public SourceBalanceId: string;
  public LockedBalanceId: string | null;
  public OriginalInventoryStatusCode: string;
  public WarehouseId: string;
  public WarehouseCode: string | null;
  public OwnerId: string;
  public OwnerCode: string | null;
  public SkuId: string;
  public SkuCode: string | null;
  public LocationId: string;
  public LocationCode: string | null;
  public UomId: string | null;
  public UomCode: string | null;
  public LpnCode: string | null;
  public ExpectedQuantity: number;
  public CountedQuantity: number | null;
  public VarianceQuantity: number | null;
  public ToleranceQuantity: number;
  public ApprovalRequestId: string | null;
  public LockTransactionId: string | null;
  public SubmitIdempotencyKey: string | null;
  public SubmitPayloadFingerprint: string | null;
  public AdjustmentTransactionId: string | null;
  public AdjustmentIdempotencyKey: string | null;
  public AdjustmentPayloadFingerprint: string | null;
  public UnlockTransactionId: string | null;
  public UnlockIdempotencyKey: string | null;
  public UnlockPayloadFingerprint: string | null;
  public CreateIdempotencyKey: string;
  public CreatePayloadFingerprint: string;
  public ReasonCode: string | null;
  public ReasonCodeId: string | null;
  public ReasonNote: string | null;
  public EvidenceRefs: string[];
  public readonly CreatedAt: Date;
  public UpdatedAt: Date;
  public CreatedBy: string | null;
  public UpdatedBy: string | null;

  constructor(props: CycleCountWorkEntityProps) {
    const now = new Date();
    this.Id = props.Id ?? randomUUID();
    this.CountCode = props.CountCode;
    this.WorkStatus = props.WorkStatus;
    this.SourceBalanceId = props.SourceBalanceId;
    this.LockedBalanceId = props.LockedBalanceId ?? null;
    this.OriginalInventoryStatusCode = props.OriginalInventoryStatusCode;
    this.WarehouseId = props.WarehouseId;
    this.WarehouseCode = props.WarehouseCode ?? null;
    this.OwnerId = props.OwnerId;
    this.OwnerCode = props.OwnerCode ?? null;
    this.SkuId = props.SkuId;
    this.SkuCode = props.SkuCode ?? null;
    this.LocationId = props.LocationId;
    this.LocationCode = props.LocationCode ?? null;
    this.UomId = props.UomId ?? null;
    this.UomCode = props.UomCode ?? null;
    this.LpnCode = props.LpnCode ?? null;
    this.ExpectedQuantity = props.ExpectedQuantity;
    this.CountedQuantity = props.CountedQuantity ?? null;
    this.VarianceQuantity = props.VarianceQuantity ?? null;
    this.ToleranceQuantity = props.ToleranceQuantity ?? 0;
    this.ApprovalRequestId = props.ApprovalRequestId ?? null;
    this.LockTransactionId = props.LockTransactionId ?? null;
    this.SubmitIdempotencyKey = props.SubmitIdempotencyKey ?? null;
    this.SubmitPayloadFingerprint = props.SubmitPayloadFingerprint ?? null;
    this.AdjustmentTransactionId = props.AdjustmentTransactionId ?? null;
    this.AdjustmentIdempotencyKey = props.AdjustmentIdempotencyKey ?? null;
    this.AdjustmentPayloadFingerprint = props.AdjustmentPayloadFingerprint ?? null;
    this.UnlockTransactionId = props.UnlockTransactionId ?? null;
    this.UnlockIdempotencyKey = props.UnlockIdempotencyKey ?? null;
    this.UnlockPayloadFingerprint = props.UnlockPayloadFingerprint ?? null;
    this.CreateIdempotencyKey = props.CreateIdempotencyKey;
    this.CreatePayloadFingerprint = props.CreatePayloadFingerprint;
    this.ReasonCode = props.ReasonCode ?? null;
    this.ReasonCodeId = props.ReasonCodeId ?? null;
    this.ReasonNote = props.ReasonNote ?? null;
    this.EvidenceRefs = props.EvidenceRefs ?? [];
    this.CreatedAt = props.CreatedAt ?? now;
    this.UpdatedAt = props.UpdatedAt ?? now;
    this.CreatedBy = props.CreatedBy ?? null;
    this.UpdatedBy = props.UpdatedBy ?? null;
  }
}
