import { randomUUID } from 'crypto';
import { InventoryTransactionStatus } from '@modules/InventoryExecution/Domain/Enums/InventoryTransactionStatus';
import { InventoryTransactionType } from '@modules/InventoryExecution/Domain/Enums/InventoryTransactionType';

export interface InventoryTransactionEntityProps {
  Id?: string;
  TransactionCode: string;
  TransactionType: InventoryTransactionType;
  TransactionStatus: InventoryTransactionStatus;
  PutawayTaskId?: string | null;
  PutawayTaskCode?: string | null;
  InventoryMovementId?: string | null;
  OwnerId: string;
  OwnerCode?: string | null;
  WarehouseId: string;
  WarehouseCode?: string | null;
  SkuId: string;
  SkuCode?: string | null;
  UomId?: string | null;
  UomCode?: string | null;
  Quantity: number;
  FromInventoryStatusCode: string;
  ToInventoryStatusCode: string;
  FromLocationId?: string | null;
  FromLocationCode?: string | null;
  ToLocationId: string;
  ToLocationCode: string;
  LpnCode?: string | null;
  SsccCode?: string | null;
  IdempotencyKey: string;
  OutboxMessageId?: string | null;
  ReasonCode?: string | null;
  ReasonCodeId?: string | null;
  ReasonNote?: string | null;
  EvidenceRefs?: string[];
  PostedAt: Date;
  PostedBy?: string | null;
  CreatedAt?: Date;
  UpdatedAt?: Date;
}

export class InventoryTransactionEntity {
  public readonly Id: string;
  public TransactionCode: string;
  public TransactionType: InventoryTransactionType;
  public TransactionStatus: InventoryTransactionStatus;
  public PutawayTaskId: string | null;
  public PutawayTaskCode: string | null;
  public InventoryMovementId: string | null;
  public OwnerId: string;
  public OwnerCode: string | null;
  public WarehouseId: string;
  public WarehouseCode: string | null;
  public SkuId: string;
  public SkuCode: string | null;
  public UomId: string | null;
  public UomCode: string | null;
  public Quantity: number;
  public FromInventoryStatusCode: string;
  public ToInventoryStatusCode: string;
  public FromLocationId: string | null;
  public FromLocationCode: string | null;
  public ToLocationId: string;
  public ToLocationCode: string;
  public LpnCode: string | null;
  public SsccCode: string | null;
  public IdempotencyKey: string;
  public OutboxMessageId: string | null;
  public ReasonCode: string | null;
  public ReasonCodeId: string | null;
  public ReasonNote: string | null;
  public EvidenceRefs: string[];
  public PostedAt: Date;
  public PostedBy: string | null;
  public readonly CreatedAt: Date;
  public UpdatedAt: Date;

  constructor(props: InventoryTransactionEntityProps) {
    const now = new Date();
    this.Id = props.Id ?? randomUUID();
    this.TransactionCode = props.TransactionCode;
    this.TransactionType = props.TransactionType;
    this.TransactionStatus = props.TransactionStatus;
    this.PutawayTaskId = props.PutawayTaskId ?? null;
    this.PutawayTaskCode = props.PutawayTaskCode ?? null;
    this.InventoryMovementId = props.InventoryMovementId ?? null;
    this.OwnerId = props.OwnerId;
    this.OwnerCode = props.OwnerCode ?? null;
    this.WarehouseId = props.WarehouseId;
    this.WarehouseCode = props.WarehouseCode ?? null;
    this.SkuId = props.SkuId;
    this.SkuCode = props.SkuCode ?? null;
    this.UomId = props.UomId ?? null;
    this.UomCode = props.UomCode ?? null;
    this.Quantity = props.Quantity;
    this.FromInventoryStatusCode = props.FromInventoryStatusCode;
    this.ToInventoryStatusCode = props.ToInventoryStatusCode;
    this.FromLocationId = props.FromLocationId ?? null;
    this.FromLocationCode = props.FromLocationCode ?? null;
    this.ToLocationId = props.ToLocationId;
    this.ToLocationCode = props.ToLocationCode;
    this.LpnCode = props.LpnCode ?? null;
    this.SsccCode = props.SsccCode ?? null;
    this.IdempotencyKey = props.IdempotencyKey;
    this.OutboxMessageId = props.OutboxMessageId ?? null;
    this.ReasonCode = props.ReasonCode ?? null;
    this.ReasonCodeId = props.ReasonCodeId ?? null;
    this.ReasonNote = props.ReasonNote ?? null;
    this.EvidenceRefs = props.EvidenceRefs ?? [];
    this.PostedAt = props.PostedAt;
    this.PostedBy = props.PostedBy ?? null;
    this.CreatedAt = props.CreatedAt ?? now;
    this.UpdatedAt = props.UpdatedAt ?? now;
  }
}
