import { randomUUID } from 'crypto';
import { PutawayTaskStatus } from '@modules/InventoryExecution/Domain/Enums/PutawayTaskStatus';

export interface PutawayTaskEntityProps {
  Id?: string;
  TaskCode: string;
  TaskStatus: PutawayTaskStatus;
  InboundPutawayReleaseId: string;
  ReceiptId: string;
  ReceiptLineId: string;
  InboundPlanId: string;
  InboundPlanLineId: string;
  InboundLpnId?: string | null;
  OwnerId: string;
  OwnerCode?: string | null;
  WarehouseId: string;
  WarehouseCode?: string | null;
  SkuId: string;
  SkuCode?: string | null;
  UomId: string;
  UomCode?: string | null;
  Quantity: number;
  LpnCode?: string | null;
  SsccCode?: string | null;
  LotNumber?: string | null;
  ExpiryDate?: Date | null;
  SerialNumber?: string | null;
  InventoryStatusCode: string;
  SourceLocationId?: string | null;
  SourceLocationCode?: string | null;
  TargetLocationId: string;
  TargetLocationCode: string;
  TargetLocationProfileId?: string | null;
  Priority: number;
  WorkPoolCode?: string | null;
  AssignedUserId?: string | null;
  ConstraintJson?: Record<string, unknown> | null;
  EligibilityDecisionJson?: Record<string, unknown> | null;
  OutboxMessageId?: string | null;
  MobileTaskId?: string | null;
  ReasonCode?: string | null;
  ReasonCodeId?: string | null;
  ReasonNote?: string | null;
  EvidenceRefs?: string[];
  IdempotencyKey: string;
  ReleasedAt: Date;
  ReleasedBy?: string | null;
  CreatedAt?: Date;
  UpdatedAt?: Date;
}

export class PutawayTaskEntity {
  public readonly Id: string;
  public TaskCode: string;
  public TaskStatus: PutawayTaskStatus;
  public InboundPutawayReleaseId: string;
  public ReceiptId: string;
  public ReceiptLineId: string;
  public InboundPlanId: string;
  public InboundPlanLineId: string;
  public InboundLpnId: string | null;
  public OwnerId: string;
  public OwnerCode: string | null;
  public WarehouseId: string;
  public WarehouseCode: string | null;
  public SkuId: string;
  public SkuCode: string | null;
  public UomId: string;
  public UomCode: string | null;
  public Quantity: number;
  public LpnCode: string | null;
  public SsccCode: string | null;
  public LotNumber: string | null;
  public ExpiryDate: Date | null;
  public SerialNumber: string | null;
  public InventoryStatusCode: string;
  public SourceLocationId: string | null;
  public SourceLocationCode: string | null;
  public TargetLocationId: string;
  public TargetLocationCode: string;
  public TargetLocationProfileId: string | null;
  public Priority: number;
  public WorkPoolCode: string | null;
  public AssignedUserId: string | null;
  public ConstraintJson: Record<string, unknown> | null;
  public EligibilityDecisionJson: Record<string, unknown> | null;
  public OutboxMessageId: string | null;
  public MobileTaskId: string | null;
  public ReasonCode: string | null;
  public ReasonCodeId: string | null;
  public ReasonNote: string | null;
  public EvidenceRefs: string[];
  public IdempotencyKey: string;
  public ReleasedAt: Date;
  public ReleasedBy: string | null;
  public readonly CreatedAt: Date;
  public UpdatedAt: Date;

  constructor(props: PutawayTaskEntityProps) {
    const now = new Date();
    this.Id = props.Id ?? randomUUID();
    this.TaskCode = props.TaskCode;
    this.TaskStatus = props.TaskStatus;
    this.InboundPutawayReleaseId = props.InboundPutawayReleaseId;
    this.ReceiptId = props.ReceiptId;
    this.ReceiptLineId = props.ReceiptLineId;
    this.InboundPlanId = props.InboundPlanId;
    this.InboundPlanLineId = props.InboundPlanLineId;
    this.InboundLpnId = props.InboundLpnId ?? null;
    this.OwnerId = props.OwnerId;
    this.OwnerCode = props.OwnerCode ?? null;
    this.WarehouseId = props.WarehouseId;
    this.WarehouseCode = props.WarehouseCode ?? null;
    this.SkuId = props.SkuId;
    this.SkuCode = props.SkuCode ?? null;
    this.UomId = props.UomId;
    this.UomCode = props.UomCode ?? null;
    this.Quantity = props.Quantity;
    this.LpnCode = props.LpnCode ?? null;
    this.SsccCode = props.SsccCode ?? null;
    this.LotNumber = props.LotNumber ?? null;
    this.ExpiryDate = props.ExpiryDate ?? null;
    this.SerialNumber = props.SerialNumber ?? null;
    this.InventoryStatusCode = props.InventoryStatusCode;
    this.SourceLocationId = props.SourceLocationId ?? null;
    this.SourceLocationCode = props.SourceLocationCode ?? null;
    this.TargetLocationId = props.TargetLocationId;
    this.TargetLocationCode = props.TargetLocationCode;
    this.TargetLocationProfileId = props.TargetLocationProfileId ?? null;
    this.Priority = props.Priority;
    this.WorkPoolCode = props.WorkPoolCode ?? null;
    this.AssignedUserId = props.AssignedUserId ?? null;
    this.ConstraintJson = props.ConstraintJson ?? null;
    this.EligibilityDecisionJson = props.EligibilityDecisionJson ?? null;
    this.OutboxMessageId = props.OutboxMessageId ?? null;
    this.MobileTaskId = props.MobileTaskId ?? null;
    this.ReasonCode = props.ReasonCode ?? null;
    this.ReasonCodeId = props.ReasonCodeId ?? null;
    this.ReasonNote = props.ReasonNote ?? null;
    this.EvidenceRefs = props.EvidenceRefs ?? [];
    this.IdempotencyKey = props.IdempotencyKey;
    this.ReleasedAt = props.ReleasedAt;
    this.ReleasedBy = props.ReleasedBy ?? null;
    this.CreatedAt = props.CreatedAt ?? now;
    this.UpdatedAt = props.UpdatedAt ?? now;
  }
}
