import { randomUUID } from 'crypto';
import { ReplenishmentTaskStatus } from '@modules/InventoryExecution/Domain/Enums/ReplenishmentTaskStatus';
import { ReplenishmentTriggerType } from '@modules/InventoryExecution/Domain/Enums/ReplenishmentTriggerType';

export interface ReplenishmentTaskEntityProps {
  Id?: string;
  TaskCode: string;
  TaskStatus: ReplenishmentTaskStatus;
  TriggerType: ReplenishmentTriggerType;
  SourceBalanceId: string;
  SourceDimensionId: string;
  SourceLocationId: string;
  SourceLocationCode?: string | null;
  SourceInventoryStatusCode: string;
  TargetLocationId: string;
  TargetLocationCode?: string | null;
  TargetLocationProfileId?: string | null;
  WarehouseId: string;
  WarehouseCode?: string | null;
  OwnerId: string;
  OwnerCode?: string | null;
  SkuId: string;
  SkuCode?: string | null;
  UomId?: string | null;
  UomCode?: string | null;
  Quantity: number;
  ShortPickReference?: string | null;
  Priority?: number | null;
  WorkPoolCode?: string | null;
  AssignedUserId?: string | null;
  EligibilityDecisionJson?: Record<string, unknown> | null;
  OutboxMessageId?: string | null;
  ConfirmTransactionId?: string | null;
  ConfirmMovementId?: string | null;
  ConfirmOutboxMessageId?: string | null;
  ReleaseIdempotencyKey: string;
  ReleasePayloadFingerprint: string;
  ConfirmIdempotencyKey?: string | null;
  ConfirmPayloadFingerprint?: string | null;
  CancelIdempotencyKey?: string | null;
  CancelPayloadFingerprint?: string | null;
  ReasonCode?: string | null;
  ReasonCodeId?: string | null;
  ReasonNote?: string | null;
  EvidenceRefs?: string[];
  ReleasedAt?: Date | null;
  ReleasedBy?: string | null;
  ConfirmedAt?: Date | null;
  ConfirmedBy?: string | null;
  CancelledAt?: Date | null;
  CancelledBy?: string | null;
  CreatedAt?: Date;
  UpdatedAt?: Date;
  CreatedBy?: string | null;
  UpdatedBy?: string | null;
}

export class ReplenishmentTaskEntity {
  public readonly Id: string;
  public TaskCode: string;
  public TaskStatus: ReplenishmentTaskStatus;
  public TriggerType: ReplenishmentTriggerType;
  public SourceBalanceId: string;
  public SourceDimensionId: string;
  public SourceLocationId: string;
  public SourceLocationCode: string | null;
  public SourceInventoryStatusCode: string;
  public TargetLocationId: string;
  public TargetLocationCode: string | null;
  public TargetLocationProfileId: string | null;
  public WarehouseId: string;
  public WarehouseCode: string | null;
  public OwnerId: string;
  public OwnerCode: string | null;
  public SkuId: string;
  public SkuCode: string | null;
  public UomId: string | null;
  public UomCode: string | null;
  public Quantity: number;
  public ShortPickReference: string | null;
  public Priority: number | null;
  public WorkPoolCode: string | null;
  public AssignedUserId: string | null;
  public EligibilityDecisionJson: Record<string, unknown> | null;
  public OutboxMessageId: string | null;
  public ConfirmTransactionId: string | null;
  public ConfirmMovementId: string | null;
  public ConfirmOutboxMessageId: string | null;
  public ReleaseIdempotencyKey: string;
  public ReleasePayloadFingerprint: string;
  public ConfirmIdempotencyKey: string | null;
  public ConfirmPayloadFingerprint: string | null;
  public CancelIdempotencyKey: string | null;
  public CancelPayloadFingerprint: string | null;
  public ReasonCode: string | null;
  public ReasonCodeId: string | null;
  public ReasonNote: string | null;
  public EvidenceRefs: string[];
  public ReleasedAt: Date | null;
  public ReleasedBy: string | null;
  public ConfirmedAt: Date | null;
  public ConfirmedBy: string | null;
  public CancelledAt: Date | null;
  public CancelledBy: string | null;
  public readonly CreatedAt: Date;
  public UpdatedAt: Date;
  public CreatedBy: string | null;
  public UpdatedBy: string | null;

  constructor(props: ReplenishmentTaskEntityProps) {
    const now = new Date();
    this.Id = props.Id ?? randomUUID();
    this.TaskCode = props.TaskCode;
    this.TaskStatus = props.TaskStatus;
    this.TriggerType = props.TriggerType;
    this.SourceBalanceId = props.SourceBalanceId;
    this.SourceDimensionId = props.SourceDimensionId;
    this.SourceLocationId = props.SourceLocationId;
    this.SourceLocationCode = props.SourceLocationCode ?? null;
    this.SourceInventoryStatusCode = props.SourceInventoryStatusCode;
    this.TargetLocationId = props.TargetLocationId;
    this.TargetLocationCode = props.TargetLocationCode ?? null;
    this.TargetLocationProfileId = props.TargetLocationProfileId ?? null;
    this.WarehouseId = props.WarehouseId;
    this.WarehouseCode = props.WarehouseCode ?? null;
    this.OwnerId = props.OwnerId;
    this.OwnerCode = props.OwnerCode ?? null;
    this.SkuId = props.SkuId;
    this.SkuCode = props.SkuCode ?? null;
    this.UomId = props.UomId ?? null;
    this.UomCode = props.UomCode ?? null;
    this.Quantity = props.Quantity;
    this.ShortPickReference = props.ShortPickReference ?? null;
    this.Priority = props.Priority ?? null;
    this.WorkPoolCode = props.WorkPoolCode ?? null;
    this.AssignedUserId = props.AssignedUserId ?? null;
    this.EligibilityDecisionJson = props.EligibilityDecisionJson ?? null;
    this.OutboxMessageId = props.OutboxMessageId ?? null;
    this.ConfirmTransactionId = props.ConfirmTransactionId ?? null;
    this.ConfirmMovementId = props.ConfirmMovementId ?? null;
    this.ConfirmOutboxMessageId = props.ConfirmOutboxMessageId ?? null;
    this.ReleaseIdempotencyKey = props.ReleaseIdempotencyKey;
    this.ReleasePayloadFingerprint = props.ReleasePayloadFingerprint;
    this.ConfirmIdempotencyKey = props.ConfirmIdempotencyKey ?? null;
    this.ConfirmPayloadFingerprint = props.ConfirmPayloadFingerprint ?? null;
    this.CancelIdempotencyKey = props.CancelIdempotencyKey ?? null;
    this.CancelPayloadFingerprint = props.CancelPayloadFingerprint ?? null;
    this.ReasonCode = props.ReasonCode ?? null;
    this.ReasonCodeId = props.ReasonCodeId ?? null;
    this.ReasonNote = props.ReasonNote ?? null;
    this.EvidenceRefs = props.EvidenceRefs ?? [];
    this.ReleasedAt = props.ReleasedAt ?? null;
    this.ReleasedBy = props.ReleasedBy ?? null;
    this.ConfirmedAt = props.ConfirmedAt ?? null;
    this.ConfirmedBy = props.ConfirmedBy ?? null;
    this.CancelledAt = props.CancelledAt ?? null;
    this.CancelledBy = props.CancelledBy ?? null;
    this.CreatedAt = props.CreatedAt ?? now;
    this.UpdatedAt = props.UpdatedAt ?? now;
    this.CreatedBy = props.CreatedBy ?? null;
    this.UpdatedBy = props.UpdatedBy ?? null;
  }
}
