import { LocationStatus } from '@modules/MasterData/Domain/Enums/LocationStatus';

export class LocationEntity {
  public readonly Id: string;
  public WarehouseId: string;
  public ZoneId: string;
  public ParentLocationId: string | null;
  public LocationCode: string;
  public LocationName: string;
  public LocationType: string;
  public LocationProfileId: string;
  public LocationStatus: LocationStatus;
  public CapacityQty: number | null;
  public CapacityVolume: number | null;
  public CapacityWeight: number | null;
  public AisleCode: string | null;
  public RackCode: string | null;
  public LevelCode: string | null;
  public BinCode: string | null;
  public PalletSlot: number | null;
  public TemperatureClass: string | null;
  public DgCompatibilityGroup: string | null;
  public BondedFlag: boolean;
  public OwnerRestriction: string | null;
  public MixSkuPolicy: string | null;
  public MixLotPolicy: string | null;
  public MixOwnerPolicy: string | null;
  public PickSequence: number | null;
  public PutawaySequence: number | null;
  public SourceSystem: string | null;
  public ReferenceId: string | null;
  public readonly CreatedAt: Date;
  public UpdatedAt: Date;
  public CreatedBy: string | null;
  public UpdatedBy: string | null;

  constructor(params: {
    Id: string;
    WarehouseId: string;
    ZoneId: string;
    ParentLocationId?: string | null;
    LocationCode: string;
    LocationName: string;
    LocationType: string;
    LocationProfileId: string;
    LocationStatus: LocationStatus;
    CapacityQty?: number | null;
    CapacityVolume?: number | null;
    CapacityWeight?: number | null;
    AisleCode?: string | null;
    RackCode?: string | null;
    LevelCode?: string | null;
    BinCode?: string | null;
    PalletSlot?: number | null;
    TemperatureClass?: string | null;
    DgCompatibilityGroup?: string | null;
    BondedFlag?: boolean | null;
    OwnerRestriction?: string | null;
    MixSkuPolicy?: string | null;
    MixLotPolicy?: string | null;
    MixOwnerPolicy?: string | null;
    PickSequence?: number | null;
    PutawaySequence?: number | null;
    SourceSystem?: string | null;
    ReferenceId?: string | null;
    CreatedAt: Date;
    UpdatedAt: Date;
    CreatedBy?: string | null;
    UpdatedBy?: string | null;
  }) {
    this.Id = params.Id;
    this.WarehouseId = params.WarehouseId;
    this.ZoneId = params.ZoneId;
    this.ParentLocationId = params.ParentLocationId ?? null;
    this.LocationCode = params.LocationCode;
    this.LocationName = params.LocationName;
    this.LocationType = params.LocationType;
    this.LocationProfileId = params.LocationProfileId;
    this.LocationStatus = params.LocationStatus;
    this.CapacityQty = params.CapacityQty ?? null;
    this.CapacityVolume = params.CapacityVolume ?? null;
    this.CapacityWeight = params.CapacityWeight ?? null;
    this.AisleCode = params.AisleCode ?? null;
    this.RackCode = params.RackCode ?? null;
    this.LevelCode = params.LevelCode ?? null;
    this.BinCode = params.BinCode ?? null;
    this.PalletSlot = params.PalletSlot ?? null;
    this.TemperatureClass = params.TemperatureClass ?? null;
    this.DgCompatibilityGroup = params.DgCompatibilityGroup ?? null;
    this.BondedFlag = params.BondedFlag ?? false;
    this.OwnerRestriction = params.OwnerRestriction ?? null;
    this.MixSkuPolicy = params.MixSkuPolicy ?? null;
    this.MixLotPolicy = params.MixLotPolicy ?? null;
    this.MixOwnerPolicy = params.MixOwnerPolicy ?? null;
    this.PickSequence = params.PickSequence ?? null;
    this.PutawaySequence = params.PutawaySequence ?? null;
    this.SourceSystem = params.SourceSystem ?? null;
    this.ReferenceId = params.ReferenceId ?? null;
    this.CreatedAt = params.CreatedAt;
    this.UpdatedAt = params.UpdatedAt;
    this.CreatedBy = params.CreatedBy ?? null;
    this.UpdatedBy = params.UpdatedBy ?? null;
  }
}
