import { SkuStatus } from '@modules/MasterData/Domain/Enums/SkuStatus';

export class SkuEntity {
  public readonly Id: string;
  public SkuCode: string;
  public SkuName: string;
  public DefaultOwnerId: string | null;
  public ItemClass: string;
  public ItemStatus: SkuStatus;
  public BaseUomId: string;
  public InventoryUomId: string;
  public LotControlled: boolean;
  public ExpiryControlled: boolean;
  public SerialControlled: boolean;
  public OwnerControlled: boolean;
  public LpnControlled: boolean;
  public TemperatureControlled: boolean;
  public DgControlled: boolean;
  public CustomsControlled: boolean;
  public QcRequired: boolean;
  public TemperatureClass: string | null;
  public DgClass: string | null;
  public BondedFlag: boolean;
  public ShelfLifeDays: number | null;
  public MinRemainingShelfLifeDays: number | null;
  public SourceSystem: string | null;
  public ReferenceId: string | null;
  public readonly CreatedAt: Date;
  public UpdatedAt: Date;
  public CreatedBy: string | null;
  public UpdatedBy: string | null;

  constructor(params: {
    Id: string;
    SkuCode: string;
    SkuName: string;
    DefaultOwnerId?: string | null;
    ItemClass: string;
    ItemStatus: SkuStatus;
    BaseUomId: string;
    InventoryUomId: string;
    LotControlled?: boolean;
    ExpiryControlled?: boolean;
    SerialControlled?: boolean;
    OwnerControlled?: boolean;
    LpnControlled?: boolean;
    TemperatureControlled?: boolean;
    DgControlled?: boolean;
    CustomsControlled?: boolean;
    QcRequired?: boolean;
    TemperatureClass?: string | null;
    DgClass?: string | null;
    BondedFlag?: boolean;
    ShelfLifeDays?: number | null;
    MinRemainingShelfLifeDays?: number | null;
    SourceSystem?: string | null;
    ReferenceId?: string | null;
    CreatedAt: Date;
    UpdatedAt: Date;
    CreatedBy?: string | null;
    UpdatedBy?: string | null;
  }) {
    this.Id = params.Id;
    this.SkuCode = params.SkuCode;
    this.SkuName = params.SkuName;
    this.DefaultOwnerId = params.DefaultOwnerId ?? null;
    this.ItemClass = params.ItemClass;
    this.ItemStatus = params.ItemStatus;
    this.BaseUomId = params.BaseUomId;
    this.InventoryUomId = params.InventoryUomId;
    this.LotControlled = params.LotControlled ?? false;
    this.ExpiryControlled = params.ExpiryControlled ?? false;
    this.SerialControlled = params.SerialControlled ?? false;
    this.OwnerControlled = params.OwnerControlled ?? false;
    this.LpnControlled = params.LpnControlled ?? false;
    this.TemperatureControlled = params.TemperatureControlled ?? false;
    this.DgControlled = params.DgControlled ?? false;
    this.CustomsControlled = params.CustomsControlled ?? false;
    this.QcRequired = params.QcRequired ?? false;
    this.TemperatureClass = params.TemperatureClass ?? null;
    this.DgClass = params.DgClass ?? null;
    this.BondedFlag = params.BondedFlag ?? false;
    this.ShelfLifeDays = params.ShelfLifeDays ?? null;
    this.MinRemainingShelfLifeDays = params.MinRemainingShelfLifeDays ?? null;
    this.SourceSystem = params.SourceSystem ?? null;
    this.ReferenceId = params.ReferenceId ?? null;
    this.CreatedAt = params.CreatedAt;
    this.UpdatedAt = params.UpdatedAt;
    this.CreatedBy = params.CreatedBy ?? null;
    this.UpdatedBy = params.UpdatedBy ?? null;
  }
}
