import { ActionCode } from '@modules/AccessControl/Domain/Enums/ActionCode';
import { ObjectType } from '@modules/AccessControl/Domain/Enums/ObjectType';
import { ActorType } from '@modules/AccessControl/Domain/Enums/ActorType';
import { AuditResult } from '@modules/AccessControl/Domain/Enums/AuditResult';

/** Input to IAuditWriter.Append. Id/OccurredAt are generated by the writer. */
export interface AuditEntry {
  ActorUserId?: string | null;
  ActorRoleCodes?: string[];
  ActorType: ActorType;
  Action: ActionCode;
  ObjectType: ObjectType;
  ObjectId?: string | null;
  ObjectCode?: string | null;
  BeforeJson?: Record<string, unknown> | null;
  AfterJson?: Record<string, unknown> | null;
  ReasonCodeId?: string | null;
  ReasonNote?: string | null;
  EvidenceRefs?: unknown[] | null;
  ReferenceType?: string | null;
  ReferenceId?: string | null;
  WarehouseId?: string | null;
  OwnerId?: string | null;
  ScopeJson?: Record<string, unknown> | null;
  CorrelationId?: string | null;
  RequestId?: string | null;
  IpAddress?: string | null;
  UserAgent?: string | null;
  Result?: AuditResult;
}
