import { PackageCheckResult } from '@modules/Outbound/Domain/Enums/PackageCheckResult';
import { PackSessionStatus } from '@modules/Outbound/Domain/Enums/PackSessionStatus';

export class PackSessionEntity {
  public readonly Id: string;
  public SessionNumber: string;
  public PickTaskId: string;
  public MobileTaskId: string | null;
  public OutboundOrderId: string;
  public WarehouseProfileId: string;
  public WarehouseId: string | null;
  public WarehouseCode: string | null;
  public OwnerId: string | null;
  public OwnerCode: string | null;
  public Status: PackSessionStatus;
  public CheckRequired: boolean;
  public CheckResult: PackageCheckResult;
  public CheckExceptionCaseId: string | null;
  public CheckReasonCode: string | null;
  public CheckReasonCodeId: string | null;
  public CheckReasonNote: string | null;
  public CheckEvidenceRefs: string[];
  public CheckPayloadJson: Record<string, unknown> | null;
  public CheckIdempotencyKey: string | null;
  public CheckPayloadFingerprint: string | null;
  public StartedAt: Date;
  public StartedBy: string | null;
  public CheckedAt: Date | null;
  public CheckedBy: string | null;
  public IdempotencyKey: string;
  public PayloadFingerprint: string;
  public readonly CreatedAt: Date;
  public UpdatedAt: Date;

  constructor(params: {
    Id: string;
    SessionNumber: string;
    PickTaskId: string;
    MobileTaskId?: string | null;
    OutboundOrderId: string;
    WarehouseProfileId: string;
    WarehouseId?: string | null;
    WarehouseCode?: string | null;
    OwnerId?: string | null;
    OwnerCode?: string | null;
    Status: PackSessionStatus;
    CheckRequired: boolean;
    CheckResult?: PackageCheckResult;
    CheckExceptionCaseId?: string | null;
    CheckReasonCode?: string | null;
    CheckReasonCodeId?: string | null;
    CheckReasonNote?: string | null;
    CheckEvidenceRefs?: string[];
    CheckPayloadJson?: Record<string, unknown> | null;
    CheckIdempotencyKey?: string | null;
    CheckPayloadFingerprint?: string | null;
    StartedAt: Date;
    StartedBy?: string | null;
    CheckedAt?: Date | null;
    CheckedBy?: string | null;
    IdempotencyKey: string;
    PayloadFingerprint: string;
    CreatedAt: Date;
    UpdatedAt: Date;
  }) {
    this.Id = params.Id;
    this.SessionNumber = params.SessionNumber;
    this.PickTaskId = params.PickTaskId;
    this.MobileTaskId = params.MobileTaskId ?? null;
    this.OutboundOrderId = params.OutboundOrderId;
    this.WarehouseProfileId = params.WarehouseProfileId;
    this.WarehouseId = params.WarehouseId ?? null;
    this.WarehouseCode = params.WarehouseCode ?? null;
    this.OwnerId = params.OwnerId ?? null;
    this.OwnerCode = params.OwnerCode ?? null;
    this.Status = params.Status;
    this.CheckRequired = params.CheckRequired;
    this.CheckResult = params.CheckResult ?? PackageCheckResult.Pending;
    this.CheckExceptionCaseId = params.CheckExceptionCaseId ?? null;
    this.CheckReasonCode = params.CheckReasonCode ?? null;
    this.CheckReasonCodeId = params.CheckReasonCodeId ?? null;
    this.CheckReasonNote = params.CheckReasonNote ?? null;
    this.CheckEvidenceRefs = params.CheckEvidenceRefs ?? [];
    this.CheckPayloadJson = params.CheckPayloadJson ?? null;
    this.CheckIdempotencyKey = params.CheckIdempotencyKey ?? null;
    this.CheckPayloadFingerprint = params.CheckPayloadFingerprint ?? null;
    this.StartedAt = params.StartedAt;
    this.StartedBy = params.StartedBy ?? null;
    this.CheckedAt = params.CheckedAt ?? null;
    this.CheckedBy = params.CheckedBy ?? null;
    this.IdempotencyKey = params.IdempotencyKey;
    this.PayloadFingerprint = params.PayloadFingerprint;
    this.CreatedAt = params.CreatedAt;
    this.UpdatedAt = params.UpdatedAt;
  }
}
