import { LabelBlockingDecision } from '@modules/BarcodeLabel/Domain/Enums/LabelBlockingDecision';
import { PackageCheckResult } from '@modules/Outbound/Domain/Enums/PackageCheckResult';
import { PackageStatus } from '@modules/Outbound/Domain/Enums/PackageStatus';

export class PackageEntity {
  public readonly Id: string;
  public PackageCode: string;
  public PackSessionId: string;
  public PickTaskId: string;
  public OutboundOrderId: string;
  public WarehouseProfileId: string;
  public WarehouseId: string | null;
  public WarehouseCode: string | null;
  public OwnerId: string | null;
  public OwnerCode: string | null;
  public Status: PackageStatus;
  public CheckRequired: boolean;
  public CheckResult: PackageCheckResult;
  public CartonType: string;
  public Weight: number | null;
  public Length: number | null;
  public Width: number | null;
  public Height: number | null;
  public LabelBlockingDecision: LabelBlockingDecision | null;
  public LabelPrintJobId: string | null;
  public LabelPrintJobCode: string | null;
  public ReadyForStagingIdempotencyKey: string | null;
  public ReadyForStagingPayloadFingerprint: string | null;
  public CloseIdempotencyKey: string | null;
  public ClosePayloadFingerprint: string | null;
  public ClosedAt: Date | null;
  public ClosedBy: string | null;
  public ReadyForStagingAt: Date | null;
  public ReadyForStagingBy: string | null;
  public IdempotencyKey: string;
  public PayloadFingerprint: string;
  public CreatedAt: Date;
  public UpdatedAt: Date;
  public CreatedBy: string | null;
  public UpdatedBy: string | null;

  constructor(params: {
    Id: string;
    PackageCode: string;
    PackSessionId: string;
    PickTaskId: string;
    OutboundOrderId: string;
    WarehouseProfileId: string;
    WarehouseId?: string | null;
    WarehouseCode?: string | null;
    OwnerId?: string | null;
    OwnerCode?: string | null;
    Status: PackageStatus;
    CheckRequired: boolean;
    CheckResult: PackageCheckResult;
    CartonType: string;
    Weight?: number | null;
    Length?: number | null;
    Width?: number | null;
    Height?: number | null;
    LabelBlockingDecision?: LabelBlockingDecision | null;
    LabelPrintJobId?: string | null;
    LabelPrintJobCode?: string | null;
    ReadyForStagingIdempotencyKey?: string | null;
    ReadyForStagingPayloadFingerprint?: string | null;
    CloseIdempotencyKey?: string | null;
    ClosePayloadFingerprint?: string | null;
    ClosedAt?: Date | null;
    ClosedBy?: string | null;
    ReadyForStagingAt?: Date | null;
    ReadyForStagingBy?: string | null;
    IdempotencyKey: string;
    PayloadFingerprint: string;
    CreatedAt: Date;
    UpdatedAt: Date;
    CreatedBy?: string | null;
    UpdatedBy?: string | null;
  }) {
    this.Id = params.Id;
    this.PackageCode = params.PackageCode;
    this.PackSessionId = params.PackSessionId;
    this.PickTaskId = params.PickTaskId;
    this.OutboundOrderId = params.OutboundOrderId;
    this.WarehouseProfileId = params.WarehouseProfileId;
    this.WarehouseId = params.WarehouseId ?? null;
    this.WarehouseCode = params.WarehouseCode ?? null;
    this.OwnerId = params.OwnerId ?? null;
    this.OwnerCode = params.OwnerCode ?? null;
    this.Status = params.Status;
    this.CheckRequired = params.CheckRequired;
    this.CheckResult = params.CheckResult;
    this.CartonType = params.CartonType;
    this.Weight = params.Weight ?? null;
    this.Length = params.Length ?? null;
    this.Width = params.Width ?? null;
    this.Height = params.Height ?? null;
    this.LabelBlockingDecision = params.LabelBlockingDecision ?? null;
    this.LabelPrintJobId = params.LabelPrintJobId ?? null;
    this.LabelPrintJobCode = params.LabelPrintJobCode ?? null;
    this.ReadyForStagingIdempotencyKey = params.ReadyForStagingIdempotencyKey ?? null;
    this.ReadyForStagingPayloadFingerprint = params.ReadyForStagingPayloadFingerprint ?? null;
    this.CloseIdempotencyKey = params.CloseIdempotencyKey ?? null;
    this.ClosePayloadFingerprint = params.ClosePayloadFingerprint ?? null;
    this.ClosedAt = params.ClosedAt ?? null;
    this.ClosedBy = params.ClosedBy ?? null;
    this.ReadyForStagingAt = params.ReadyForStagingAt ?? null;
    this.ReadyForStagingBy = params.ReadyForStagingBy ?? null;
    this.IdempotencyKey = params.IdempotencyKey;
    this.PayloadFingerprint = params.PayloadFingerprint;
    this.CreatedAt = params.CreatedAt;
    this.UpdatedAt = params.UpdatedAt;
    this.CreatedBy = params.CreatedBy ?? null;
    this.UpdatedBy = params.UpdatedBy ?? null;
  }
}
