import { PickTaskStatus } from '@modules/Outbound/Domain/Enums/PickTaskStatus';
import { PickExceptionType } from '@modules/Outbound/Domain/Enums/PickExceptionType';
import { PickSubstitutionStatus } from '@modules/Outbound/Domain/Enums/PickSubstitutionStatus';

export class PickTaskEntity {
  public readonly Id: string;
  public PickReleaseId: string;
  public OutboundOrderId: string;
  public AllocationId: string;
  public AllocationLineId: string;
  public OutboundOrderLineId: string;
  public TaskNumber: string;
  public Status: PickTaskStatus;
  public Sequence: number;
  public BatchNumber: string | null;
  public SourceBalanceId: string;
  public SourceDimensionId: string;
  public SourceLocationId: string;
  public TargetLocationId: string | null;
  public TargetReference: string | null;
  public SkuId: string;
  public SkuCode: string | null;
  public UomId: string;
  public UomCode: string | null;
  public Quantity: number;
  public InventoryStatusCode: string | null;
  public LotNumber: string | null;
  public SerialNumber: string | null;
  public ExpiryDate: Date | null;
  public CompletedAt: Date | null;
  public CompletedBy: string | null;
  public ConfirmIdempotencyKey: string | null;
  public ConfirmPayloadFingerprint: string | null;
  public ConfirmOutboxMessageId: string | null;
  public ConfirmInventoryTransactionId: string | null;
  public ConfirmResultJson: Record<string, unknown> | null;
  public ExceptionType: PickExceptionType | null;
  public ExceptionCaseId: string | null;
  public ExceptionReasonCode: string | null;
  public ExceptionReasonCodeId: string | null;
  public ExceptionReasonNote: string | null;
  public ExceptionEvidenceJson: Record<string, unknown> | null;
  public ExceptionIdempotencyKey: string | null;
  public ExceptionPayloadFingerprint: string | null;
  public ExceptionReportedAt: Date | null;
  public ExceptionReportedBy: string | null;
  public ReplenishmentRequired: boolean;
  public ReplenishmentTaskId: string | null;
  public SubstitutionStatus: PickSubstitutionStatus | null;
  public SubstitutionSkuId: string | null;
  public SubstitutionSkuCode: string | null;
  public SubstitutionUomId: string | null;
  public SubstitutionUomCode: string | null;
  public SubstitutionQuantity: number | null;
  public SubstitutionApprovalRequestId: string | null;
  public SubstitutionPolicyJson: Record<string, unknown> | null;
  public SubstitutionIdempotencyKey: string | null;
  public SubstitutionPayloadFingerprint: string | null;
  public SubstitutionRequestedAt: Date | null;
  public SubstitutionRequestedBy: string | null;
  public readonly CreatedAt: Date;

  constructor(params: {
    Id: string;
    PickReleaseId: string;
    OutboundOrderId: string;
    AllocationId: string;
    AllocationLineId: string;
    OutboundOrderLineId: string;
    TaskNumber: string;
    Status: PickTaskStatus;
    Sequence: number;
    BatchNumber?: string | null;
    SourceBalanceId: string;
    SourceDimensionId: string;
    SourceLocationId: string;
    TargetLocationId?: string | null;
    TargetReference?: string | null;
    SkuId: string;
    SkuCode?: string | null;
    UomId: string;
    UomCode?: string | null;
    Quantity: number;
    InventoryStatusCode?: string | null;
    LotNumber?: string | null;
    SerialNumber?: string | null;
    ExpiryDate?: Date | null;
    CompletedAt?: Date | null;
    CompletedBy?: string | null;
    ConfirmIdempotencyKey?: string | null;
    ConfirmPayloadFingerprint?: string | null;
    ConfirmOutboxMessageId?: string | null;
    ConfirmInventoryTransactionId?: string | null;
    ConfirmResultJson?: Record<string, unknown> | null;
    ExceptionType?: PickExceptionType | null;
    ExceptionCaseId?: string | null;
    ExceptionReasonCode?: string | null;
    ExceptionReasonCodeId?: string | null;
    ExceptionReasonNote?: string | null;
    ExceptionEvidenceJson?: Record<string, unknown> | null;
    ExceptionIdempotencyKey?: string | null;
    ExceptionPayloadFingerprint?: string | null;
    ExceptionReportedAt?: Date | null;
    ExceptionReportedBy?: string | null;
    ReplenishmentRequired?: boolean;
    ReplenishmentTaskId?: string | null;
    SubstitutionStatus?: PickSubstitutionStatus | null;
    SubstitutionSkuId?: string | null;
    SubstitutionSkuCode?: string | null;
    SubstitutionUomId?: string | null;
    SubstitutionUomCode?: string | null;
    SubstitutionQuantity?: number | null;
    SubstitutionApprovalRequestId?: string | null;
    SubstitutionPolicyJson?: Record<string, unknown> | null;
    SubstitutionIdempotencyKey?: string | null;
    SubstitutionPayloadFingerprint?: string | null;
    SubstitutionRequestedAt?: Date | null;
    SubstitutionRequestedBy?: string | null;
    CreatedAt: Date;
  }) {
    this.Id = params.Id;
    this.PickReleaseId = params.PickReleaseId;
    this.OutboundOrderId = params.OutboundOrderId;
    this.AllocationId = params.AllocationId;
    this.AllocationLineId = params.AllocationLineId;
    this.OutboundOrderLineId = params.OutboundOrderLineId;
    this.TaskNumber = params.TaskNumber;
    this.Status = params.Status;
    this.Sequence = params.Sequence;
    this.BatchNumber = params.BatchNumber ?? null;
    this.SourceBalanceId = params.SourceBalanceId;
    this.SourceDimensionId = params.SourceDimensionId;
    this.SourceLocationId = params.SourceLocationId;
    this.TargetLocationId = params.TargetLocationId ?? null;
    this.TargetReference = params.TargetReference ?? null;
    this.SkuId = params.SkuId;
    this.SkuCode = params.SkuCode ?? null;
    this.UomId = params.UomId;
    this.UomCode = params.UomCode ?? null;
    this.Quantity = params.Quantity;
    this.InventoryStatusCode = params.InventoryStatusCode ?? null;
    this.LotNumber = params.LotNumber ?? null;
    this.SerialNumber = params.SerialNumber ?? null;
    this.ExpiryDate = params.ExpiryDate ?? null;
    this.CompletedAt = params.CompletedAt ?? null;
    this.CompletedBy = params.CompletedBy ?? null;
    this.ConfirmIdempotencyKey = params.ConfirmIdempotencyKey ?? null;
    this.ConfirmPayloadFingerprint = params.ConfirmPayloadFingerprint ?? null;
    this.ConfirmOutboxMessageId = params.ConfirmOutboxMessageId ?? null;
    this.ConfirmInventoryTransactionId = params.ConfirmInventoryTransactionId ?? null;
    this.ConfirmResultJson = params.ConfirmResultJson ?? null;
    this.ExceptionType = params.ExceptionType ?? null;
    this.ExceptionCaseId = params.ExceptionCaseId ?? null;
    this.ExceptionReasonCode = params.ExceptionReasonCode ?? null;
    this.ExceptionReasonCodeId = params.ExceptionReasonCodeId ?? null;
    this.ExceptionReasonNote = params.ExceptionReasonNote ?? null;
    this.ExceptionEvidenceJson = params.ExceptionEvidenceJson ?? null;
    this.ExceptionIdempotencyKey = params.ExceptionIdempotencyKey ?? null;
    this.ExceptionPayloadFingerprint = params.ExceptionPayloadFingerprint ?? null;
    this.ExceptionReportedAt = params.ExceptionReportedAt ?? null;
    this.ExceptionReportedBy = params.ExceptionReportedBy ?? null;
    this.ReplenishmentRequired = params.ReplenishmentRequired ?? false;
    this.ReplenishmentTaskId = params.ReplenishmentTaskId ?? null;
    this.SubstitutionStatus = params.SubstitutionStatus ?? null;
    this.SubstitutionSkuId = params.SubstitutionSkuId ?? null;
    this.SubstitutionSkuCode = params.SubstitutionSkuCode ?? null;
    this.SubstitutionUomId = params.SubstitutionUomId ?? null;
    this.SubstitutionUomCode = params.SubstitutionUomCode ?? null;
    this.SubstitutionQuantity = params.SubstitutionQuantity ?? null;
    this.SubstitutionApprovalRequestId = params.SubstitutionApprovalRequestId ?? null;
    this.SubstitutionPolicyJson = params.SubstitutionPolicyJson ?? null;
    this.SubstitutionIdempotencyKey = params.SubstitutionIdempotencyKey ?? null;
    this.SubstitutionPayloadFingerprint = params.SubstitutionPayloadFingerprint ?? null;
    this.SubstitutionRequestedAt = params.SubstitutionRequestedAt ?? null;
    this.SubstitutionRequestedBy = params.SubstitutionRequestedBy ?? null;
    this.CreatedAt = params.CreatedAt;
  }
}
